adding:
  dependencies:
    config:
      - field.field.comment.comment.comment_body
    module:
      - text
  content:
    comment_body:
      type: text_textarea
      weight: 11
      region: content
      settings:
        rows: 5
        placeholder: ''
      third_party_settings: {  }
removing: {  }
