adding:
  dependencies:
    config:
      - filter.format.restricted_html
    module:
      - contact
      - filter
      - media
      - system
  permissions:
    - 'access site-wide contact form'
    - 'use text format restricted_html'
    - 'access content'
    - 'view media'
removing: {  }
