adding:
  dependencies:
    config:
      - field.field.comment.comment.comment_body
    module:
      - text
  content:
    comment_body:
      type: text_default
      label: hidden
      settings: {  }
      third_party_settings: {  }
      weight: 0
      region: content
removing: {  }
