adding:
  dependencies:
    config:
      - node.type.article
      - node.type.page
      - taxonomy.vocabulary.tags
    module:
      - contextual
      - file
      - node
      - path
      - system
      - taxonomy
  permissions:
    - 'access contextual links'
    - 'access files overview'
    - 'access administration pages'
    - 'access content overview'
    - 'administer url aliases'
    - 'create article content'
    - 'create page content'
    - 'create terms in tags'
    - 'create url aliases'
    - 'delete article revisions'
    - 'delete own article content'
    - 'delete own page content'
    - 'delete page revisions'
    - 'edit own article content'
    - 'edit own page content'
    - 'edit terms in tags'
    - 'revert all revisions'
    - 'view all revisions'
    - 'view own unpublished content'
    - 'view the administration theme'
removing: {  }
