adding:
  dependencies:
    config:
      - field.field.user.user.user_picture
      - image.style.thumbnail
    module:
      - image
  content:
    user_picture:
      type: image
      label: hidden
      settings:
        image_link: content
        image_style: thumbnail
      third_party_settings: {  }
      weight: 0
      region: content
removing: {  }
