<?php

/**
 * @file
 * Contains winebow_shopmodal.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function winebow_shopmodal_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
    // Main module help for the winebow_shopmodal module.
    case 'help.page.winebow_shopmodal':
        $output = '';
        $output .= '<h3>' . t('About') . '</h3>';
        $output .= '<p>' . t('Shop Modal for states markets and contacting sales departments') . '</p>';
        return $output;

    default:
    }
}

/**
 * Implements hook_theme().
 */
function winebow_shopmodal_theme() {
  return [
    'winebow_shopmodal_block' => [
      'variables' => [
        'data' => NULL
      ],
      'template' => 'winebow-shopmodal-block',
    ],
    'winebow_shopmodal_modal' => [
      'variables' => [
        'data' => NULL
      ],
      'template' => 'winebow-shopmodal-modal',
    ],
  ];
}


/**
* @param $ variables
* Implements hook_preprocess_page()
*/
function winebow_shopmodal_preprocess_page(&$variables)
{

    $logged_in = \Drupal::currentUser()->isAuthenticated();
    if (!$logged_in) {
        // Add libraries for anonymous
        $libraries['#attached']['library'][] = 'core/drupal.ajax';
        render($libraries);
    }

}
